model_info:
  - name: 'google/gemma-2-9b'
    type: 'base'
  - name: 'google/gemma-2-9b-it'
    type: 'code'

dataset: "mbpp"

sparsity_ratio: 0.5

nsamples: 15

components:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

base_model_type: 'base'
base_model_name: 'google/gemma-2-9b'

target_model_names:
  code: 'google/gemma-2-9b-it'

global_parameters:
  normalize: true
  int8_mask: true

prefix_mapping:
  q_proj: 'self_attn.q_proj'
  k_proj: 'self_attn.k_proj'
  v_proj: 'self_attn.v_proj'
  o_proj: 'self_attn.o_proj'
  gate_proj: 'mlp.gate_proj'
  up_proj: 'mlp.up_proj'
  down_proj: 'mlp.down_proj'

